# Generated by Django 4.2.7 on 2023-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownAreas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownCapacitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacitacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownCarreras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownContratoOpcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_contrato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownEmpleoSituacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_empleo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownEmpleoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_empleo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownEspecializaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especializacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownInstituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownNivelEducativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownRegimenAseguramiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen_aseguramiento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownRegimenLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen_laboral', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownRolProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_titulo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownSedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownSituacionesEspeciales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_especial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownTipoContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('dleg', models.CharField(max_length=100)),
            ],
        ),
    ]
