# Generated by Django 4.2.7 on 2023-11-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('usuario_nombres', models.CharField(max_length=100)),
                ('usuario_apellidos', models.CharField(max_length=100)),
                ('usuario_correo', models.EmailField(max_length=254, unique=True)),
                ('usuario_contrasenia', models.CharField(max_length=100)),
                ('usuario_sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('NE', 'No Especificado')], max_length=15)),
                ('usuario_telefono', models.CharField(max_length=50)),
                ('id_usuario_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dropdownroles')),
            ],
        ),
    ]
