# Generated by Django 4.2.7 on 2023-11-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_valor_basico', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_asigfam_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_asignacion_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_bono_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sueldo_monto_bono', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_anual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajador', unique=True)),
            ],
        ),
    ]
