# Generated by Django 4.2.7 on 2023-11-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='trabajador_relacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajador'),
        ),
    ]
