# Generated by Django 4.2.7 on 2023-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGlobales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField()),
                ('remuneracion_minima_vital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
