# Generated by Django 4.2.7 on 2023-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trabajador_trabajador_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='trabajador_path_doc_estado_civil',
            field=models.FileField(blank=True, null=True, upload_to='docs/estados_civiles/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='trabajador_path_documento',
            field=models.FileField(blank=True, null=True, upload_to='docs/identidades/'),
        ),
    ]
