# Generated by Django 4.2.7 on 2023-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_usuario_apellidos_usuario_usuario_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='trabajador_estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cesado', 'Cesado')], default='Activo', max_length=15),
        ),
    ]
