# Generated by Django 4.2.7 on 2023-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_trabajador_trabajador_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='trabajador_estado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cesado', 'Cesado')], default='Activo', max_length=15),
        ),
    ]
