# Generated by Django 4.2.7 on 2023-12-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_trabajador_trabajador_estado_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sueldo',
            name='sueldo_asigfam_porcentaje',
        ),
        migrations.RemoveField(
            model_name='sueldo',
            name='sueldo_asignacion_familiar',
        ),
        migrations.RemoveField(
            model_name='sueldo',
            name='sueldo_bono_porcentaje',
        ),
        migrations.AddField(
            model_name='sueldo',
            name='sueldo_monto_asigfam',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='sueldo_opc_asigfam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='sueldo_opc_bono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='sueldo_porcentaje_bono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo_anual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo_monto_bono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
