# Generated by Django 4.2.7 on 2023-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_trabajador_trabajador_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='trabajador_record',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
